### ISSUE TITLE
Error with stopping

### ISSUE THREAD

**Issue by lolteam4u** [Sybsuper/SybHideAndSeek#1]
[17:20:19 INFO]: zachary13 issued server command: /hideandseek stop
[17:20:19 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'hideandseek' in plugin SybHideAndSeek v1.3.1
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-307]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-307]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Paper-307]
at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1860) ~[patched_1.15.2.jar:git-Paper-307]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1668) ~[patched_1.15.2.jar:git-Paper-307]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-307]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-307]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-307]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-307]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-307]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-307]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-307]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1097) ~[patched_1.15.2.jar:git-Paper-307]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1090) ~[patched_1.15.2.jar:git-Paper-307]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-307]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1164) ~[patched_1.15.2.jar:git-Paper-307]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-307]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NullPointerException
at me.sybsuper.SybHideAndSeek.Main.stopGame(Main.java:98) ~[?:?]
at me.sybsuper.SybHideAndSeek.Main.onCommand(Main.java:123) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-307]
... 17 more
[17:20:32 INFO]: zachary13 issued server command: /thru
[17:20:36 INFO]: zachary13 issued server command: /thru
[17:20:37 INFO]: zachary13 issued server command: /thru
[17:20:38 INFO]: zachary13 issued server command: /thru
[17:20:47 INFO]: zachary13 issued server command: /hideandseek
[17:20:50 INFO]: zachary13 issued server command: /hideandseek Yoreni
[17:21:01 INFO]: Yoreni issued server command: /gmsp
[17:21:09 INFO]: Yoreni issued server command: /gmc
[17:21:19 INFO]: Yoreni issued server command: /gmc
container:~/$

**Comment by lolteam4u** [comment]
1.15.2 Paper

**Comment by lolteam4u** [comment]
Doesnt freeze the Seeker Either he can run around on 1.15.2 Im finding evverything today
